version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.*"
          - "AspNetCore.*"
      observability:
        patterns:
          - "OpenTelemetry.*"
          - "Serilog*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
